In [ ]:
#Raising exceptions
#an exception acn be raised forcefully by using the raise clause in python.
#it is useful in that scenario where we need to raise an exception to stop the xecution of the program 



In [1]:
def ageCheck(age):
    if age>=18:
        print("you can vote")
    else:
        raise ValueError

ageCheck(15)


ValueError: 

In [3]:
def ageCheck(age):
    if age>=18:
        print("you can vote")
    else:
        raise ValueError("wait some year")

ageCheck(15)

ValueError: wait some year

In [5]:
def ageCheck(age):
    if age>=18:
        print("you can vote")
    else:
        raise ValueError("you cant vote")
try:
    ageCheck(15)
except ValueError as e:
    print(e)


you cant vote


In [ ]:
#numpy


In [9]:
import numpy as np
l= [10,30,25,43,21]
np.array(l)

array([10, 30, 25, 43, 21])

In [19]:
a = np.array (42)
b = np.array ([1, 2, 3, 4, 5])
c = np.array ([[1, 2, 3], [4, 5, 6]])
d = np.array ([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print ("a array", a)
print ("b array", b)
print ("c array ", c)
print("d array",d)

a array 42
b array [1 2 3 4 5]
c array  [[1 2 3]
 [4 5 6]]
d array [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [25]:
a = np.array (42)
b = np.array ([1, 2, 3, 4, 5])
c = np.array ([[1, 2, 3], [4, 5, 6]])
d = np.array ([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print ("a array", a)
print ("b array", b)
print ("c array ", c)
print("d array",d)
print ("a array dimen ",a.ndim)
print ("b array dimen",b.ndim)
print ("c array dimen",c.ndim)
print("d array dimen",d.ndim)

a array 42
b array [1 2 3 4 5]
c array  [[1 2 3]
 [4 5 6]]
d array [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
a array dimen  0
b array dimen 1
c array dimen 2
d array dimen 3


In [ ]:
#shape
#1d array: vector
#2d array:metrix
#3d array:tensor

In [50]:
arr= np.array([1,2,3,4,5,6,7])
print("arr array shape",arr.shape)
arr=np.array ([[1, 2, 3], [4, 5, 6]])
print("arr array shape",arr.shape)

arr array shape (7,)
arr array shape (2, 3)


In [ ]:
#slicing
#aceesing subset of sequences

In [31]:
arr= np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2 4]


In [44]:
arr= np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])
sarr=arr[1:5]
print(arr)
print(sarr)
sarr[2]=100
print(arr)
print(sarr)



[2 4]
[1 2 3 4 5 6 7]
[2 3 4 5]
[  1   2   3 100   5   6   7]
[  2   3 100   5]


In [ ]:
#copy
#no changes in original array

In [56]:
arr = np.array ([1, 2, 3, 4, 5])
arr2= arr. copy ()
arr[0]= 42
print(arr)
print(arr2)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
#view
#change in original array too

In [58]:
arr = np.array ([1, 2, 3, 4, 5])
arr2= arr. view ()
arr[0]= 42
print(arr)
print(arr2)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
#numpy zeros() in Python
#The numpy.zeros) function is one of the most significant functions which is used in machine learning programs widely. This function is used to generate an array containing zeros.
#The numpy.zeros() function provide a new array of given shape and type, which is filled with zeros. numpy. zeros () without dtype and order import numpy as np a=np. zeros (6)
#2: numpy.zeros() without order import numpy as np a=np. zeros ((6, ), dtype=int)
#3: numpy.zeros() with shape import numpy as np a=np. zeros ( (6,2))
#4: numpy.zeros with the shape

In [60]:
a=np.zeros((5,2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
#numpy ones() in python

In [72]:
a=np.ones((5,2))
a

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [79]:
a=np.ones((5,2))*10
a

array([[10., 10.],
       [10., 10.],
       [10., 10.],
       [10., 10.],
       [10., 10.]])

In [81]:
a=np.ones(5,dtype=int)
a

array([1, 1, 1, 1, 1])

In [ ]:
#The eye tool returns a 2-D array with 1's as the diagonal and0's elsewhere. 
#The diagonal can be main,upper, or lower depending on the optional parameter k. A positive k is for the upper diagonal, a negative k is for the lower, and a 0 k (default) is for the main diagonal.

In [101]:
arr4=np.eye(3)
print(arr4)

arr4=np.eye(3,4)
print(arr4)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [109]:
arr4=np. eye (3)
print(arr4)
arr4=np.eye (3,4)
print(arr4)
arr5=np. diag( (3,4,1,6))
print(arr5)
print(arr5.ndim)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[3 0 0 0]
 [0 4 0 0]
 [0 0 1 0]
 [0 0 0 6]]
2
