In [ ]:
#randint() is an inbuilt Function of the randon module in Python. 
#The randos module gives access to vartous suseful functions one of then being able to generate random numbers, which is randint()


In [9]:
import numpy as np
rand=np.random.randint(0,10,2)
print(rand)

[2 6]


In [17]:
rand=np.random.rand(4)

print(rand)

rand=np.random.rand(2,3)

print(rand)

arr=np.random.randint(0, 100, 12)

print(arr)


[0.18940843 0.93613409 0.9579998  0.59190645]
[[0.01512254 0.81466398 0.15057659]
 [0.75998149 0.46901011 0.42140101]]
[60  4 93 85 31 85 59 65 45 22 47 90]


In [ ]:
#The reshape function in NumPy allows you to change the shape (dimensions) of an array without changing its data. This can be useful when you want to rearrange the way data is organized in an array, such as converting a 1-dimensional array into a 2-dimensional matrix or vice versa, or changing the size of a multi-dimensional array while maintaining the total number of elements.

In [31]:
arr=np.random.randint(0,100,12)
print(arr)
arr=arr.reshape(4,3)
print(arr)
print("Array values is ", arr [0] [1])
print("Array values is",arr [1] [0])
print(arr.shape)
arr=arr.reshape(-1,4)
print(arr)
arr=arr.reshape(2,-1)
print(arr)

[97 88 31  1 18  6  3 42 94  5 32  2]
[[97 88 31]
 [ 1 18  6]
 [ 3 42 94]
 [ 5 32  2]]
Array values is  88
Array values is 1
(4, 3)
[[97 88 31  1]
 [18  6  3 42]
 [94  5 32  2]]
[[97 88 31  1 18  6]
 [ 3 42 94  5 32  2]]


In [ ]:
#seed

In [37]:
np.random.seed(145)
arr=np.random.randint(0,100,12)
print(arr)

[37 86 87 18 90 69  8 53 33 32 40 26]


In [41]:
import numpy as n

ar=n.array([1,20,5,9,3,4,8,5,6,2,25, 2,2265,3,33,])

slicing=ar [4:9]

print("new slicing ", slicing)

print("new array ",ar)

print (type (slicing))

print (type (ar))

slicing[:]=0

print("old Slicing ", slicing)

print("old array ",ar)

new slicing  [3 4 8 5 6]
new array  [   1   20    5    9    3    4    8    5    6    2   25    2 2265    3
   33]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
old Slicing  [0 0 0 0 0]
old array  [   1   20    5    9    0    0    0    0    0    2   25    2 2265    3
   33]


In [49]:
#arange: to generate the numbers in sequence

In [51]:
ar=np.arange(1,15)
print(ar)
print(ar[ar%2==0])
print(ar[ar%2!=0])
print(ar[ar>8])
ar[ar%2==0]=0
print(ar)
arr=n.arange(1,8)
print(arr+2)
print(arr*2)
print(arr**2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 2  4  6  8 10 12 14]
[ 1  3  5  7  9 11 13]
[ 9 10 11 12 13 14]
[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0]
[3 4 5 6 7 8 9]
[ 2  4  6  8 10 12 14]
[ 1  4  9 16 25 36 49]


In [53]:
arr=n.array([10,20,30,25,6,2])
print(n.min(arr))
print(n.max(arr))
print(n.argmin(arr))
print(n.sqrt(arr))
print(n.sin(arr))
print(n.cos(arr))

2
30
5
[3.16227766 4.47213595 5.47722558 5.         2.44948974 1.41421356]
[-0.54402111  0.91294525 -0.98803162 -0.13235175 -0.2794155   0.90929743]
[-0.83907153  0.40808206  0.15425145  0.99120281  0.96017029 -0.41614684]


In [55]:
import numpy as n
n.random.seed(122)
mat=n.random.randint(1,21,9).reshape(3,3)
print(mat)
print(n.sum(mat))
print(n.cumsum(mat))
print(n.min(mat))
print(n.max(mat))
print("-------------")
print(n.sum(mat,axis=1)) 
print(n.min(mat,axis=1)) 
print(n.max(mat,axis=1))
print(n.cumsum(mat,axis=1))

[[16 11 13]
 [17 13 16]
 [ 3 16 11]]
116
[ 16  27  40  57  70  86  89 105 116]
3
17
-------------
[40 46 30]
[11 13  3]
[16 17 16]
[[16 27 40]
 [17 30 46]
 [ 3 19 30]]


In [ ]:
#shuffle 
#unique

In [65]:
import numpy as n
n.random.seed(122)
mat=n.random.randint(1, 21, 10)
print(mat)
n.random.shuffle(mat)
print(mat)
print(n.unique(mat, return_index=True,return_counts=True) )
print(n.unique(mat).size)

[16 11 13 17 13 16  3 16 11 10]
[13 16 16 11 16 10 11 13 17  3]
(array([ 3, 10, 11, 13, 16, 17]), array([9, 5, 3, 0, 1, 8], dtype=int64), array([1, 1, 2, 2, 3, 1], dtype=int64))
6
