In [ ]:
# Convert the below list into numpy array then display the array
#Input: my_list = (1, 2, 3, 4, 5)

In [1]:
import numpy as np

# Given list
my_list = [1, 2, 3, 4, 5]

# Convert the list to a NumPy array
my_array = np.array(my_list)

# Display the array
print(my_array)

[1 2 3 4 5]


In [ ]:
#Convert the below list into a numpy array then display the array then display the first and last index and then multiply each element by 2 and display the result.
#Input: my_ list = [1, 2, 3, 4, 5]

In [3]:
import numpy as np

# Given list
my_list = [1, 2, 3, 4, 5]

# Convert the list to a NumPy array
my_array = np.array(my_list)

# Display the array
print("Array:", my_array)

# Display the first and last index
print("First element:", my_array[0])
print("Last element:", my_array[-1])

# Multiply each element by 2
multiplied_array = my_array * 2

# Display the result
print("Multiplied array:", multiplied_array)

Array: [1 2 3 4 5]
First element: 1
Last element: 5
Multiplied array: [ 2  4  6  8 10]


In [ ]:
#write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives.

In [7]:
import numpy as np

# Create an array of 10 zeros
zeros_array = np.zeros(10)

# Create an array of 10 ones
ones_array = np.ones(10)

# Create an array of 10 fives
fives_array = np.full(10, 5)

# Display the arrays
print("Array of 10 zeros:",zeros_array)
print("Array of 10 ones:",ones_array)
print("Array of 10 fives:",fives_array)

Array of 10 zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array of 10 ones: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Array of 10 fives: [5 5 5 5 5 5 5 5 5 5]


In [ ]:
#Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

In [9]:
import numpy as np

# Create a 3x3 matrix with values ranging from 2 to 10
matrix = np.arange(2, 11).reshape(3, 3)

# Display the matrix
print("3x3 matrix with values ranging from 2 to 10:")
print(matrix)

3x3 matrix with values ranging from 2 to 10:
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [ ]:
#Calculate the total revenue generated by two product categories in a storeInput
#category _revenue = пр array(500, 600, 700, 550))
#categon2 reverve = np ara (450, 700, 800 60)

In [15]:
import numpy as np

# Revenue from category 1
category1_revenue = np.array([500, 600, 700, 550])

# Revenue from category 2
category2_revenue = np.array([450, 700, 800, 60])

# Calculate total revenue
total_revenue = (category1_revenue) +(category2_revenue)

# Display the total revenue
print("Total Revenue:",total_revenue)

Total Revenue: [ 950 1300 1500  610]


In [ ]:
#calculate the profit made by a company
#input:revenue=np.array([10000,12000,11000,10500])
#expenses=np.array([4000,5000,4500,4800])

In [28]:
import numpy as np
revenue=np.array([10000,12000,11000,10500])
expenses=np.array([4000,5000,4500,4800])
profit=revenue-expenses
print(profit)

[6000 7000 6500 5700]


In [ ]:
#detemine which product in a store are out of stock(quantity is 0)
#input:np.array([10,0,5,0,20,0])

In [30]:
import numpy as np
inventory = np.array([10, 0, 5, 0, 20, 0])

# Find the indices of products that are out of stock (quantity is 0)
out_of_stock_indices = np.where(inventory == 0)[0]

# Display the indices of out of stock products
print("Indices of out of stock products:", out_of_stock_indices)

Indices of out of stock products: [1 3 5]


In [32]:
#Calculate the total cost of items in a shopping cart, considering the quantity and price per item.
#Input:
#quantity = p.array(2, 3, 4, 1])
#price _per _item = p. array(10.0, 5.0, 8.0, 12.0])

In [38]:
import numpy as np
quantity = np.array([2, 3, 4, 1])
price_per_item = np.array([10.0, 5.0, 8.0, 12.0])
total_cost = (quantity * price_per_item)
total_cost

array([20., 15., 32., 12.])