In [ ]:
#axis (optional): The axis along which the array should be split. By default, it's 0 (split along rows).
#Here are some examples of how to use np.split:

In [15]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
# Split the array into 3 equal-sized sub-arrays
sub_arrays = np.split(arr, 3)
# Print the sub-arrays
for sub_arr in sub_arrays:
   print(sub_arr)

[1 2]
[3 4]
[5 6]


In [61]:
import numpy as np
arr = np.array([3, 1, 2, 4, 5])
# Sort the array in ascending order (creates a new sorted array)
sorted_arr = np.sort(arr)
# Print the sorted array
print("Sorted array (ascending):", sorted_arr)
# Sort the array in descending order
sorted_arr_desc = np.sort(arr)[::-1]
# Print the sorted array in descending orde

Sorted array (ascending): [1 2 3 4 5]


In [ ]:
#Sorting Along Specific Axis (For Multi-dimensional Arrays):When working with
#multi-dimensional arrays, you can specify the axis along which you want to sort. Here's
#an example:

In [63]:
import numpy as np
matrix = np.array([[3, 1, 2],
[6, 5, 4]])
# Sort along rows (axis=1) in ascending order
sorted_matrix = np.sort(matrix, axis=1)
# Print the sorted matrix
print("Sorted matrix (ascending along rows):")
print(sorted_matrix)

Sorted matrix (ascending along rows):
[[1 2 3]
 [4 5 6]]


In [ ]:
#np.concatenate():The np.concatenate() function is used to join arrays along a
#specified axis. It takes a sequence of arrays as input and concatenates them along the
#specified axis

In [65]:
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])
# Concatenate arr1 and arr2 along rows (vertical)
result = np.concatenate((arr1, arr2), axis=0)
# Print the concatenated array
print(result)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
#np.vstack(): Stacks arrays vertically (along rows).

In [69]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
# Stack arr1 and arr2 vertically
result = np.vstack((arr1, arr2))
# Print the vertically stacked array
print(result)

[[1 2 3]
 [4 5 6]]


In [ ]:
#np.hstack(): Stacks arrays horizontally (along columns).

In [71]:
import numpy as np
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
# Stack arr1 and arr2 horizontally
result = np.hstack((arr1, arr2))
# Print the horizontally stacked array
print(result)

[1 2 3 4]


In [ ]:
#Numpy Filter
#In NumPy, you can filter elements in an array based on a specified condition using
#boolean indexing. Boolean indexing allows you to create a mask (a boolean array) that
#selects elements from the original array that meet the specified condition. Here's how to
#filter elements in a NumPy array:

In [73]:
import numpy as np
# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5, 6])
# Create a boolean mask based on a condition (e.g., values greater than 3)
mask = (arr > 3)
# Use the mask to filter elements in the array
filtered_array = arr[mask]
# Print the filtered array
print("Filtered Array:", filtered_array)

Filtered Array: [4 5 6]


In [ ]:
#standard deviation

In [77]:
import numpy as np
# Score of Class A students
classA= np.array([85, 88, 90, 92, 95])
# Score of Class A students
classB= np.array([70, 80, 85, 95, 100])
classA_mean=np.mean(classA)
classB_mean=np.mean(classB)
print('Class A Score Average',classA_mean) 

Class A Score Average 90.0


In [103]:
import numpy as np
classB= np.array ([70, 80, 85, 95, 100])
classB_mean=np.mean (classB)
print ('Class B Score Average',classB_mean)
var=np.var(classB)
print ('Class B Variance is',var)
std=np.std(classB)
print('Class B Variance is', std)

Class B Score Average 86.0
Class B Variance is 114.0
Class B Variance is 10.677078252031311
