In [1]:
import numpy as np

my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)
print("NumPy Array:", my_array)


NumPy Array: [1 2 3 4 5]


In [ ]:
# Convert the below list into a numpy array then display the array then display the first and last index and then multiply each element by 2 and display the result. 
# Input: my_list = [1, 2, 3, 4, 5] 

In [3]:
import numpy as np

my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)
print("NumPy Array:", my_array)
print("First element:", my_array[0])
print("Last element:", my_array[-1])
doubled_array = my_array * 2
print("Array after multiplying each element by 2:", doubled_array)


NumPy Array: [1 2 3 4 5]
First element: 1
Last element: 5
Array after multiplying each element by 2: [ 2  4  6  8 10]


In [ ]:
# Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives. 

In [7]:
import numpy as np

zeros_array = np.zeros(10)
ones_array = np.ones(10)
fives_array = np.full(10, 5)  # Alternatively, you could use np.array([5]*10)
combined_array = np.concatenate((zeros_array, ones_array, fives_array))
print("Array of 10 zeros:", zeros_array)
print("Array of 10 ones:", ones_array)
print("Array of 10 fives:", fives_array)
print("Combined array:", combined_array)


Array of 10 zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array of 10 ones: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Array of 10 fives: [5 5 5 5 5 5 5 5 5 5]
Combined array: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]


In [ ]:
# Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10. 

In [11]:
import numpy as np

values = np.arange(2, 11)  # Generates array [2, 3, 4, 5, 6, 7, 8, 9, 10]
matrix_3x3 = values.reshape((3, 3))
print("3x3 Matrix with values ranging from 2 to 10:")
print(matrix_3x3)


3x3 Matrix with values ranging from 2 to 10:
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
